### ISSUE TITLE
Create 'Hello world'

### ISSUE THREAD

**Issue by utamons** [Miraschon/ds-#1]

**Comment by deytulsi18** [comment]
hello, I am getting started with open source, please help me getting stated and solve some beggginer issues.
May I work on this issue ?

**Comment by deytulsi18** [comment]
what do I have to do?

**Comment by utamons** [comment]
This was a student's project and it's completed. I created the issue for testing, sorry.

**Comment by utamons** [comment]
This was a student's project and it's completed. I created the issue for testing, sorry.

**Comment by utamons** [comment]
This was a student's project and it's completed. I created the issue for testing, sorry.

**Comment by utamons** [comment]
This was a student's project and it's completed. I created the issue for testing, sorry.

**Comment by utamons** [comment]
This was a student's project and it's completed. I created the issue for testing, sorry.

**Comment by utamons** [comment]
This was a student's project and it's completed. I created the issue for testing, sorry.

**Comment by utamons** [comment]
This was a student's project and it's completed. I created the issue for testing, sorry.

**Comment by utamons** [comment]
This was a student's project and it's completed. I created the issue for testing, sorry.

**Comment by utamons** [comment]
This was a student's project and it's completed. I created the issue for testing, sorry.

**Comment by utamons** [comment]
This was a student's project and it's completed. I created the issue for testing, sorry.

**Comment by utamons** [comment]
This was a student's project and it's completed. I created the issue for testing, sorry.
